### ISSUE TITLE
Only first selection got translated

### ISSUE THREAD

**Issue by pluff** [shemerey/atom-tt#3]
1. Select a text in an editor
2. push cmd+ctrl+\
3. everything works
4. get back to editor (by pressing cmd+ctrl+\ again)
5. select another text.
6. push cmd+ctrl+\
7. translation windows have old texts.

**Comment by shemerey** [comment]
This is kind of a `feature`. The purpose of doing this is to keep your text for translation unless you remove it by yourself. It keeps first input  and you can come back to it anytime you want. 

Now I think about implementing some kind of history, and push current text for translation into history and replace it with a current selection.

**Comment by pluff** [comment]
you can show "previous" translation if there is no active selection and translate new selection otherwise.

**Comment by shemerey** [comment]
@pluff check this out `v 0.7` it out

**Comment by pluff** [comment]
👍
